[General]
Name=Atmosphere

[Background]
Color=#000000
ImageFile=atmo.jpg
Type=3

[Foreground]
Color=#ffffff
Margin=40
Opacity=85
Padding=20
Position=1
Rounding=8
RoundingDisabled=0
Width=650

[ForegroundBlur]
Enabled=true
Radius=32

[ForegroundShadow]
Color=#000000
Enabled=true
Offset=2
Radius=16

[Spacings]
Alignment=0
IndentFirstLine=true
LineSpacing=150
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48

[Text]
Color=#2e3436
Font="DejaVu Serif,14,-1,5,50,0,0,0,0,0"
Misspelled=#ff0000
